### ISSUE TITLE
request for docs updating for cluster join process

### ISSUE THREAD

**Issue by zhujian7** [open-cluster-management-io/api#87]
Currently, I followed [quick start of registration](https://github.com/open-cluster-management-io/registration#quickstart) to register a cluster, and the cluster registered succeeded, but I found the docs of [cluster join process](https://github.com/open-cluster-management-io/api/blob/main/docs/clusterjoinprocess.md) is outdated. For example:
- [x] clusterrolebinding's name is not correct, I did not find any clusterrolebing named `system:open-cluster-management:clusterName:agentName` in my cluster, I think it should be `open-cluster-management:managedcluster:clusterName`(https://github.com/open-cluster-management-io/registration/pull/55 gave me some clue) 
> 5. hub-controller creates a clusterrolebinding on the hub with the identity of `system:open-cluster-management:clusterName:agentName`

The [cluster join process](https://github.com/open-cluster-management-io/api/blob/main/docs/clusterjoinprocess.md) doc is very important for newcomers to understand the whole cluster registration process, very nice if it could be updated(very pleased to try to do it by myself when I figure out the whole process). Thanks a lot.

**Comment by qiujian16** [comment]
@zhujian7 would you like to update it :) we can discuss a bit on this

**Comment by zhujian7** [comment]
> @zhujian7 would you like to update it :) we can discuss a bit on this

Of course, I’d like to.
