### ISSUE TITLE
Codegen scripts doesnt work outside GOPATH with go mod

### ISSUE THREAD

**Issue by yue9944882** [open-cluster-management-io/api#91]
if the project is outside of GOPATH directory and with the env var unset, running `make update` will generate the whole package path `open-cluster-management/api/client/...` in the project. the expected output should be omitting the extra parent paths i.e. `client/...`.

one way to fix this is to switch the code-generator to controller-gen which runs perfect in go mod mode.

**Comment by xuezhaojun** [comment]
A temporary approach: after `make update`, run:
```
cp -rf open-cluster-management.io/api/* ./ && rm -rf open-cluster-management.io
```

**Comment by qiujian16** [comment]
this is fixed

/close
